trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.1

steps:
- script: |
    ls -lia


- task: BlazeMeter Integration@2
  displayName: "BlazeMeter Test"
  inputs:
    selectTask: 'runExistingTest'
    testurl: 'https://a.blazemeter.com/app/#/accounts/$(AccounID)/workspaces/$(WorkSpaceID)/projects/2066897/tests/14772606/edit'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    selectUploadfile: 'No'